### ISSUE TITLE
Episode ends values to learn tactile representations

### ISSUE THREAD

**Issue by Jcastanyo** [ZhengtongXu/UniT#2]
Hi,

I am trying to train your model to learn tactile representations with data from my sensor. I see that in you replay_buffer.zarr data, you are also saving episode ends. Is it necessary if I'm only interesed in the tactile representation task? If I just save one number that matches the shape of my dataset, can I train the model without problems?

Thanks in advance.

**Comment by ZhengtongXu** [comment]
Yes. One episode is basically a chunk of data with shape (T, data_shape). Here T could be the total number of your images and data_shape is the size of your images.

**Comment by Jcastanyo** [comment]
Hi! 
Sorry, I forgot to reply. It worked! Thanks!
